"""
Report Generation System for Agricultural Monitoring Platform
Generates PDF reports with field condition summaries and customizable templates.
"""

import io
import base64
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Tuple
import pandas as pd
import numpy as np
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.linecharts import HorizontalLineChart
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.backends.backend_agg import FigureCanvasAgg
import seaborn as sns

# Set matplotlib backend for server environments
plt.switch_backend('Agg')
sns.set_style("whitegrid")


class ReportTemplate:
    """Base class for report templates"""
    
    def __init__(self, title: str, description: str):
        self.title = title
        self.description = description
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=colors.darkgreen
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceAfter=12,
            spaceBefore=20,
            textColor=colors.darkblue
        ))
        
        self.styles.add(ParagraphStyle(
            name='AlertHigh',
            parent=self.styles['Normal'],
            textColor=colors.red,
            fontSize=12,
            leftIndent=20
        ))
        
        self.styles.add(ParagraphStyle(
            name='AlertMedium',
            parent=self.styles['Normal'],
            textColor=colors.orange,
            fontSize=12,
            leftIndent=20
        ))
        
        self.styles.add(ParagraphStyle(
            name='AlertLow',
            parent=self.styles['Normal'],
            textColor=colors.blue,
            fontSize=12,
            leftIndent=20
        ))


class StandardReportTemplate(ReportTemplate):
    """Standard comprehensive report template"""
    
    def __init__(self):
        super().__init__(
            "Agricultural Monitoring Standard Report",
            "Comprehensive field condition analysis with vegetation indices, alerts, and recommendations"
        )
    
    def generate_content(self, data: Dict[str, Any]) -> List:
        """Generate report content elements"""
        story = []
        
        # Title page
        story.extend(self._create_title_page(data))
        story.append(PageBreak())
        
        # Executive summary
        story.extend(self._create_executive_summary(data))
        story.append(PageBreak())
        
        # Zone analysis
        story.extend(self._create_zone_analysis(data))
        story.append(PageBreak())
        
        # Vegetation indices trends
        story.extend(self._create_vegetation_trends(data))
        story.append(PageBreak())
        
        # Alert summary
        story.extend(self._create_alert_summary(data))
        story.append(PageBreak())
        
        # Recommendations
        story.extend(self._create_recommendations(data))
        
        return story
    
    def _create_title_page(self, data: Dict[str, Any]) -> List:
        """Create title page"""
        story = []
        
        # Title
        story.append(Paragraph(self.title, self.styles['CustomTitle']))
        story.append(Spacer(1, 0.5*inch))
        
        # Report info table
        report_info = [
            ['Report Date:', data.get('report_date', datetime.now().strftime('%Y-%m-%d'))],
            ['Period:', f"{data.get('start_date', 'N/A')} to {data.get('end_date', 'N/A')}"],
            ['Zones Analyzed:', str(len(data.get('zones', [])))],
            ['Generated By:', data.get('generated_by', 'Agricultural Monitoring System')]
        ]
        
        info_table = Table(report_info, colWidths=[2*inch, 3*inch])
        info_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ]))
        
        story.append(info_table)
        story.append(Spacer(1, 1*inch))
        
        # Summary statistics
        if 'summary_stats' in data:
            stats = data['summary_stats']
            story.append(Paragraph("Summary Statistics", self.styles['SectionHeader']))
            
            stats_data = [
                ['Total Area Monitored:', f"{stats.get('total_area', 0):.1f} hectares"],
                ['Active Alerts:', str(stats.get('active_alerts', 0))],
                ['Average NDVI:', f"{stats.get('avg_ndvi', 0):.3f}"],
                ['Data Quality Score:', f"{stats.get('quality_score', 0):.1f}%"]
            ]
            
            stats_table = Table(stats_data, colWidths=[2.5*inch, 2.5*inch])
            stats_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 12),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ]))
            
            story.append(stats_table)
        
        return story
    
    def _create_executive_summary(self, data: Dict[str, Any]) -> List:
        """Create executive summary section"""
        story = []
        
        story.append(Paragraph("Executive Summary", self.styles['CustomTitle']))
        story.append(Spacer(1, 0.3*inch))
        
        # Overall health assessment
        overall_health = data.get('overall_health', 'Good')
        health_color = {
            'Excellent': 'green',
            'Good': 'blue', 
            'Fair': 'orange',
            'Poor': 'red'
        }.get(overall_health, 'black')
        
        story.append(Paragraph(
            f"<b>Overall Field Health Status: <font color='{health_color}'>{overall_health}</font></b>",
            self.styles['Normal']
        ))
        story.append(Spacer(1, 0.2*inch))
        
        # Key findings
        if 'key_findings' in data:
            story.append(Paragraph("Key Findings:", self.styles['SectionHeader']))
            for finding in data['key_findings']:
                story.append(Paragraph(f"• {finding}", self.styles['Normal']))
            story.append(Spacer(1, 0.2*inch))
        
        # Critical alerts
        if 'critical_alerts' in data and data['critical_alerts']:
            story.append(Paragraph("Critical Alerts Requiring Immediate Attention:", self.styles['SectionHeader']))
            for alert in data['critical_alerts']:
                story.append(Paragraph(f"• {alert}", self.styles['AlertHigh']))
            story.append(Spacer(1, 0.2*inch))
        
        return story
    
    def _create_zone_analysis(self, data: Dict[str, Any]) -> List:
        """Create zone-by-zone analysis"""
        story = []
        
        story.append(Paragraph("Zone Analysis", self.styles['CustomTitle']))
        story.append(Spacer(1, 0.3*inch))
        
        zones = data.get('zones', [])
        
        for zone in zones:
            story.append(Paragraph(f"Zone: {zone.get('name', 'Unknown')}", self.styles['SectionHeader']))
            
            # Zone details table
            zone_details = [
                ['Crop Type:', zone.get('crop_type', 'N/A')],
                ['Area:', f"{zone.get('area', 0):.1f} hectares"],
                ['Planting Date:', zone.get('planting_date', 'N/A')],
                ['Days Since Planting:', str(zone.get('days_since_planting', 'N/A'))],
                ['Current NDVI:', f"{zone.get('current_ndvi', 0):.3f}"],
                ['NDVI Trend (30d):', zone.get('ndvi_trend', 'Stable')],
                ['Active Alerts:', str(zone.get('active_alerts', 0))]
            ]
            
            zone_table = Table(zone_details, colWidths=[2*inch, 3*inch])
            zone_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ]))
            
            story.append(zone_table)
            story.append(Spacer(1, 0.2*inch))
            
            # Zone-specific recommendations
            if 'recommendations' in zone:
                story.append(Paragraph("Recommendations:", self.styles['Normal']))
                for rec in zone['recommendations']:
                    story.append(Paragraph(f"• {rec}", self.styles['Normal']))
                story.append(Spacer(1, 0.2*inch))
        
        return story
    
    def _create_vegetation_trends(self, data: Dict[str, Any]) -> List:
        """Create vegetation indices trends section"""
        story = []
        
        story.append(Paragraph("Vegetation Index Trends", self.styles['CustomTitle']))
        story.append(Spacer(1, 0.3*inch))
        
        # Add trend charts if available
        if 'trend_charts' in data:
            for chart_data in data['trend_charts']:
                # Create matplotlib chart
                chart_image = self._create_trend_chart(chart_data)
                if chart_image:
                    story.append(chart_image)
                    story.append(Spacer(1, 0.2*inch))
        
        # Trend analysis table
        if 'trend_analysis' in data:
            story.append(Paragraph("Trend Analysis Summary", self.styles['SectionHeader']))
            
            trend_data = [['Zone', 'Index', 'Current Value', '30-Day Trend', 'Status']]
            
            for analysis in data['trend_analysis']:
                trend_data.append([
                    analysis.get('zone', ''),
                    analysis.get('index', ''),
                    f"{analysis.get('current_value', 0):.3f}",
                    analysis.get('trend', ''),
                    analysis.get('status', '')
                ])
            
            trend_table = Table(trend_data, colWidths=[1.2*inch, 0.8*inch, 1*inch, 1*inch, 1*inch])
            trend_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ]))
            
            story.append(trend_table)
        
        return story
    
    def _create_alert_summary(self, data: Dict[str, Any]) -> List:
        """Create alert summary section"""
        story = []
        
        story.append(Paragraph("Alert Summary", self.styles['CustomTitle']))
        story.append(Spacer(1, 0.3*inch))
        
        alerts = data.get('alerts', [])
        
        if not alerts:
            story.append(Paragraph("No active alerts at this time.", self.styles['Normal']))
            return story
        
        # Group alerts by severity
        alert_groups = {'critical': [], 'high': [], 'medium': [], 'low': []}
        
        for alert in alerts:
            severity = alert.get('severity', 'low').lower()
            if severity in alert_groups:
                alert_groups[severity].append(alert)
        
        # Display alerts by severity
        for severity, alert_list in alert_groups.items():
            if not alert_list:
                continue
                
            story.append(Paragraph(f"{severity.title()} Priority Alerts ({len(alert_list)})", self.styles['SectionHeader']))
            
            style_name = f'Alert{severity.title()}' if severity in ['High', 'Medium', 'Low'] else 'Normal'
            style = self.styles.get(style_name, self.styles['Normal'])
            
            for alert in alert_list:
                alert_text = f"• {alert.get('message', 'No message')} (Zone: {alert.get('zone', 'Unknown')})"
                story.append(Paragraph(alert_text, style))
            
            story.append(Spacer(1, 0.2*inch))
        
        return story
    
    def _create_recommendations(self, data: Dict[str, Any]) -> List:
        """Create recommendations section"""
        story = []
        
        story.append(Paragraph("Recommendations", self.styles['CustomTitle']))
        story.append(Spacer(1, 0.3*inch))
        
        recommendations = data.get('recommendations', [])
        
        if not recommendations:
            story.append(Paragraph("No specific recommendations at this time. Continue regular monitoring.", self.styles['Normal']))
            return story
        
        # Group recommendations by priority
        priority_groups = {'immediate': [], 'short_term': [], 'long_term': []}
        
        for rec in recommendations:
            priority = rec.get('priority', 'long_term').lower()
            if priority in priority_groups:
                priority_groups[priority].append(rec)
        
        for priority, rec_list in priority_groups.items():
            if not rec_list:
                continue
                
            story.append(Paragraph(f"{priority.replace('_', ' ').title()} Actions", self.styles['SectionHeader']))
            
            for rec in rec_list:
                story.append(Paragraph(f"• {rec.get('action', 'No action specified')}", self.styles['Normal']))
                if 'details' in rec:
                    story.append(Paragraph(f"  Details: {rec['details']}", self.styles['Normal']))
            
            story.append(Spacer(1, 0.2*inch))
        
        return story
    
    def _create_trend_chart(self, chart_data: Dict[str, Any]) -> Optional[Image]:
        """Create a trend chart using matplotlib"""
        try:
            fig, ax = plt.subplots(figsize=(8, 4))
            
            # Plot data
            dates = pd.to_datetime(chart_data.get('dates', []))
            values = chart_data.get('values', [])
            
            if len(dates) == 0 or len(values) == 0:
                return None
            
            ax.plot(dates, values, marker='o', linewidth=2, markersize=4)
            ax.set_title(chart_data.get('title', 'Vegetation Index Trend'))
            ax.set_xlabel('Date')
            ax.set_ylabel(chart_data.get('ylabel', 'Index Value'))
            
            # Format x-axis
            ax.xaxis.set_major_formatter(mdates.DateFormatter('%m/%d'))
            ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=1))
            plt.xticks(rotation=45)
            
            plt.tight_layout()
            
            # Convert to image
            buffer = io.BytesIO()
            plt.savefig(buffer, format='png', dpi=150, bbox_inches='tight')
            buffer.seek(0)
            
            # Create ReportLab Image
            img = Image(buffer, width=6*inch, height=3*inch)
            plt.close(fig)
            
            return img
            
        except Exception as e:
            print(f"Error creating trend chart: {e}")
            return None


class ExecutiveSummaryTemplate(ReportTemplate):
    """Executive summary report template"""
    
    def __init__(self):
        super().__init__(
            "Executive Summary Report",
            "High-level overview for management with key metrics and critical alerts"
        )
    
    def generate_content(self, data: Dict[str, Any]) -> List:
        """Generate executive summary content"""
        story = []
        
        # Title
        story.append(Paragraph(self.title, self.styles['CustomTitle']))
        story.append(Spacer(1, 0.3*inch))
        
        # Key metrics dashboard
        story.extend(self._create_metrics_dashboard(data))
        story.append(Spacer(1, 0.3*inch))
        
        # Critical issues
        story.extend(self._create_critical_issues(data))
        story.append(Spacer(1, 0.3*inch))
        
        # Performance summary
        story.extend(self._create_performance_summary(data))
        
        return story
    
    def _create_metrics_dashboard(self, data: Dict[str, Any]) -> List:
        """Create key metrics dashboard"""
        story = []
        
        story.append(Paragraph("Key Performance Indicators", self.styles['SectionHeader']))
        
        metrics = data.get('kpi_metrics', {})
        
        # Create metrics table
        metrics_data = [
            ['Metric', 'Current Value', 'Target', 'Status'],
            ['Overall Field Health', metrics.get('health_score', 'N/A'), '> 80%', '✓' if metrics.get('health_score', 0) > 80 else '⚠'],
            ['Average NDVI', f"{metrics.get('avg_ndvi', 0):.3f}", '> 0.6', '✓' if metrics.get('avg_ndvi', 0) > 0.6 else '⚠'],
            ['Active Critical Alerts', str(metrics.get('critical_alerts', 0)), '0', '✓' if metrics.get('critical_alerts', 0) == 0 else '⚠'],
            ['Data Coverage', f"{metrics.get('data_coverage', 0):.1f}%", '> 95%', '✓' if metrics.get('data_coverage', 0) > 95 else '⚠']
        ]
        
        metrics_table = Table(metrics_data, colWidths=[2*inch, 1.5*inch, 1*inch, 0.8*inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey])
        ]))
        
        story.append(metrics_table)
        
        return story
    
    def _create_critical_issues(self, data: Dict[str, Any]) -> List:
        """Create critical issues section"""
        story = []
        
        story.append(Paragraph("Critical Issues Requiring Attention", self.styles['SectionHeader']))
        
        critical_issues = data.get('critical_issues', [])
        
        if not critical_issues:
            story.append(Paragraph("No critical issues identified.", self.styles['Normal']))
        else:
            for issue in critical_issues:
                story.append(Paragraph(f"• {issue}", self.styles['AlertHigh']))
        
        return story
    
    def _create_performance_summary(self, data: Dict[str, Any]) -> List:
        """Create performance summary"""
        story = []
        
        story.append(Paragraph("Performance Summary", self.styles['SectionHeader']))
        
        summary = data.get('performance_summary', {})
        
        summary_text = f"""
        <b>Monitoring Period:</b> {summary.get('period', 'N/A')}<br/>
        <b>Total Area:</b> {summary.get('total_area', 0):.1f} hectares<br/>
        <b>Zones Monitored:</b> {summary.get('zones_count', 0)}<br/>
        <b>Data Points Collected:</b> {summary.get('data_points', 0):,}<br/>
        <b>System Uptime:</b> {summary.get('uptime', 0):.1f}%<br/>
        """
        
        story.append(Paragraph(summary_text, self.styles['Normal']))
        
        return story


class ReportGenerator:
    """Main report generator class"""
    
    def __init__(self):
        self.templates = {
            'standard': StandardReportTemplate(),
            'executive': ExecutiveSummaryTemplate(),
            'technical': StandardReportTemplate(),  # Can be customized later
            'field': StandardReportTemplate()  # Can be customized later
        }
    
    def generate_report(self, template_name: str, data: Dict[str, Any], 
                       output_path: Optional[str] = None) -> bytes:
        """
        Generate a PDF report using the specified template.
        
        Args:
            template_name: Name of the template to use
            data: Data dictionary containing report information
            output_path: Optional file path to save the report
            
        Returns:
            PDF content as bytes
        """
        if template_name not in self.templates:
            raise ValueError(f"Unknown template: {template_name}")
        
        template = self.templates[template_name]
        
        # Create PDF document
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        # Generate content
        story = template.generate_content(data)
        
        # Build PDF
        doc.build(story)
        
        # Get PDF content
        pdf_content = buffer.getvalue()
        buffer.close()
        
        # Save to file if path provided
        if output_path:
            with open(output_path, 'wb') as f:
                f.write(pdf_content)
        
        return pdf_content
    
    def get_available_templates(self) -> List[str]:
        """Get list of available report templates"""
        return list(self.templates.keys())
    
    def add_template(self, name: str, template: ReportTemplate) -> None:
        """Add a custom report template"""
        self.templates[name] = template


# Utility functions for data preparation
def prepare_report_data(zones: List[Dict], alerts: List[Dict], 
                       time_series_data: List[Dict], 
                       start_date: datetime, end_date: datetime) -> Dict[str, Any]:
    """
    Prepare data dictionary for report generation.
    
    Args:
        zones: List of monitoring zone data
        alerts: List of alert data
        time_series_data: List of time series measurements
        start_date: Report period start date
        end_date: Report period end date
        
    Returns:
        Formatted data dictionary for report generation
    """
    
    # Calculate summary statistics
    total_area = sum(zone.get('area', 0) for zone in zones)
    active_alerts = len([alert for alert in alerts if alert.get('status') == 'active'])
    critical_alerts = [alert for alert in alerts if alert.get('severity') == 'critical' and alert.get('status') == 'active']
    
    # Calculate average NDVI
    ndvi_values = [ts.get('mean_value', 0) for ts in time_series_data if ts.get('index_type') == 'NDVI']
    avg_ndvi = np.mean(ndvi_values) if ndvi_values else 0
    
    # Determine overall health
    health_score = avg_ndvi * 100  # Simple health score based on NDVI
    if health_score > 70:
        overall_health = 'Good'
    elif health_score > 50:
        overall_health = 'Fair'
    else:
        overall_health = 'Poor'
    
    # Prepare zone analysis
    zone_analysis = []
    for zone in zones:
        zone_alerts = [alert for alert in alerts if alert.get('zone_id') == zone.get('id')]
        zone_ts = [ts for ts in time_series_data if ts.get('zone_id') == zone.get('id') and ts.get('index_type') == 'NDVI']
        
        current_ndvi = zone_ts[-1].get('mean_value', 0) if zone_ts else 0
        
        zone_analysis.append({
            'name': zone.get('name', 'Unknown'),
            'crop_type': zone.get('crop_type', 'N/A'),
            'area': zone.get('area', 0),
            'planting_date': zone.get('planting_date', 'N/A'),
            'days_since_planting': zone.get('days_since_planting', 0),
            'current_ndvi': current_ndvi,
            'ndvi_trend': 'Stable',  # Would calculate from time series
            'active_alerts': len([a for a in zone_alerts if a.get('status') == 'active']),
            'recommendations': zone.get('recommendations', [])
        })
    
    return {
        'report_date': datetime.now().strftime('%Y-%m-%d'),
        'start_date': start_date.strftime('%Y-%m-%d'),
        'end_date': end_date.strftime('%Y-%m-%d'),
        'generated_by': 'Agricultural Monitoring System',
        'summary_stats': {
            'total_area': total_area,
            'active_alerts': active_alerts,
            'avg_ndvi': avg_ndvi,
            'quality_score': 95.0  # Mock quality score
        },
        'overall_health': overall_health,
        'key_findings': [
            f"Monitored {len(zones)} zones covering {total_area:.1f} hectares",
            f"Average NDVI across all zones: {avg_ndvi:.3f}",
            f"Currently {active_alerts} active alerts requiring attention"
        ],
        'critical_alerts': [alert.get('message', '') for alert in critical_alerts],
        'zones': zone_analysis,
        'alerts': alerts,
        'kpi_metrics': {
            'health_score': health_score,
            'avg_ndvi': avg_ndvi,
            'critical_alerts': len(critical_alerts),
            'data_coverage': 98.5
        },
        'critical_issues': [alert.get('message', '') for alert in critical_alerts],
        'performance_summary': {
            'period': f"{start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}",
            'total_area': total_area,
            'zones_count': len(zones),
            'data_points': len(time_series_data),
            'uptime': 99.2
        },
        'recommendations': [
            {
                'priority': 'immediate',
                'action': 'Address critical alerts in affected zones',
                'details': 'Focus on zones with pest risk or vegetation stress'
            },
            {
                'priority': 'short_term',
                'action': 'Monitor NDVI trends in underperforming zones',
                'details': 'Increase monitoring frequency for zones with declining trends'
            }
        ]
    }